version: '3'

services:
  web:
    build: ./source
    command: > 
      sh -c "rm -rf staticfiles
             python manage.py collectstatic --noinput
             python manage.py migrate
             gunicorn project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./source/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
